CC = g++ 
G = -g

FILE = main.cpp
TEMP = A_star.h AVLTree.h Graph.h pairKeyComp.h
OUT_FILE = prog1
build: $(FILE)
	$(CC) -std=c++11 -o $(OUT_FILE) $(FILE)
clear:
	rm -f *.o core

rebuild: clean builds
